main:
  web_trigger_build:
    - runner:
        cpus: 2
      docker:
        # 声明使用项目中的 Dockerfile 来构建环境镜像
        build: 
          dockerfile: Dockerfile
      imports:
        - https://cnb.cool/yoki.working/env/-/blob/main/sqlite.env.yml
        - https://cnb.cool/yoki.working/env/-/blob/main/llm.env.yml
        - https://cnb.cool/yoki.working/env/-/blob/main/cnb.env.yml
      services:
        - docker
      stages:
        - name: 创建制品
          script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest .
        - name: 推送镜像
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
# .cnb.yml
$:
  vscode:
    - docker:
        # 指定开发环境镜像，可以是任意可访问的镜像。
        # 如果 image 指定的镜像中已安装 code-server 代码服务，将使用单容器模式启动开发环境
        # 如果 image 指定的镜像中未安装 code-server 代码服务，将使用双容器模式启动开发环境
        # 如下镜像为 CNB 默认开发环境镜像，已安装代码服务，将使用单容器模式启动开发环境
        # 可按需替换为其他镜像
        image: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
      imports: 
        - https://cnb.cool/yoki.working/env/-/blob/main/sqlite.env.yml
        - https://cnb.cool/yoki.working/env/-/blob/main/llm.env.yml
        - https://cnb.cool/yoki.working/env/-/blob/main/cnb.env.yml
      services:
        - name: vscode
          options:
              # 超时设置为10小时 3600 * 1000 *
              keepAliveTimeout: 36000000
        - docker
      # 开发环境启动后会执行的任务
      stages:
        - name: echo hello
          script: echo "Hello"




       
